apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-app
spec:
  selector:
    matchLabels:
      app: mc-app
  replicas: 1
  template:
    metadata:
      labels:
        app: mc-app
    spec:
      containers:
      - name: mc-app
        image: memcached
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 11211
          name: mc-port
