apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-app
spec:
  selector:
    matchLabels::
      app: db-app
  replicas: 1
  template::::
    metadata::
      labels:
        app: db-app
    spec:
      containers:
      - name: myapp
        image: vprofile/vprofiledb:v1
        ports:
        - name: db-app-port
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
          - valueFrom:
              secretKeyRef:
                key: db-pass
